Create depot
glaciyan/Lagersystem-Frontend pull request #119
Opened 2024-12-03 16:03 UTC by willstef95

2024-12-09 06:56 UTC, glaciyan requested changes
Es gibt noch andere punkte, ich schau es mir später die pages nochmal genauer an. Erkläre auch noch mal was deine konkrete Idee hinter pinia storages ist.

2024-12-09 06:56 UTC, glaciyan commented on src/pages/Depot.vue
Ein name wie DepotDisplay wäre ganz gut

2024-12-09 06:56 UTC, glaciyan commented on src/pages/Depot.vue
> +      <div v-else>
Wenn es einen fehler beim laden gibt sollte man auch schauen ob errors, einträge hat

2024-12-09 06:56 UTC, glaciyan commented on src/components/Form/FormInput.vue
> +    placeholder="Please enter your depot name"
Dieser component ist für alle Inputs, nicht nur für depots. Bitte `<FormInput placeholder="..." />` benutzen

2024-12-09 06:56 UTC, glaciyan commented on src/components/Form/FormInputTextArea.vue
> +    placeholder="Please enter your depot description"
Siehe Kommentar von FormInput

2024-12-09 18:16 UTC, willstef95 commented on src/pages/Depot.vue
Erledigt

2024-12-09 18:21 UTC, willstef95 commented on src/lib/api/useApi.ts
> +    catch (error) {
Habs jetzt entfernt

2024-12-09 18:21 UTC, willstef95 commented on src/components/LSy/DepotsViewGrid.vue
> +import { defineProps, computed } from "vue";
Erledigt

2024-12-11 23:51 UTC, willstef95 commented on src/components/LSy/CreateStorage.vue
> +const props = defineProps({
erledigt

2024-12-12 11:12 UTC, glaciyan approved these changes

2024-12-12 11:12 UTC, glaciyan commented on src/components/Form/FormInput.vue
> +    placeholder="Please enter your input"
placeholderk können entfernt werden

2024-12-12 11:12 UTC, glaciyan commented on src/lib/api/config/endpoints.ts
> +    .returns(z.object({
noch in `types.ts` definieren

2024-12-12 11:12 UTC, glaciyan commented on src/router.ts
> +    name: "Depot",
Name brauchen wir hier nicht

2024-12-12 11:25 UTC, merged